---
##
## Playbook: SSH Keys für System-User konfigurieren
## Ziel: System-User für SSH-Zugriff mit Yubikey konfigurieren durch:
##   - SSH Public Keys vom Controller auf Zielhost kopieren.
##
## Ausführen (Beispiel):
##   - SSH Key auf Yubikey erstellen: "ssh-keygen -t ed25519-sk -O resident -O verify-required -O application=ssh:rp_ethnode_26021001 -C 'rp@ethnode_YubiKey5C-nano_2026-02-10_01' -f ~/.ssh/id_ed25519-sk_rp_ethnode_YubiKey5C-nano_2026-02-10_01"
##   - SSH Key auf Backup-Yubikey erstellen: "ssh-keygen -t ed25519-sk -O resident -O verify-required -O application=ssh:rp_ethnode_26021001 -C 'rp@ethnode_YubiKey5C-nfc_2026-02-10_01' -f ~/.ssh/id_ed25519-sk_rp_ethnode_YubiKey5C-nfc_2026-02-10_01"
##   - ansible-playbook -i inventory/hosts.yml --extra-vars="ansible_port=22" --extra-vars="ansible_user=rp" --extra-vars="ansible_ssh_private_key_file=" --ask-pass --ask-become-pass 02_setup_system_user.yml
##
## Targets: Inventory-Gruppe "ethnode"
## Privilege: become nötig für User-Konfiguration.
## Variablen:
##   - system_user: Benutzername des System-Users
##

- name: Setup system user
  hosts: ethnode
  become: true
  gather_facts: false

  vars_files:
    - vars/config_project.yml
    - vars/config_untracked.yml

  tasks:
    # Sicherstellen, dass .ssh-Verzeichnis mit korrekten Rechten existiert.
    - name: Ensure .ssh directory exists with strict permissions
      file:
        path: "/home/{{ system_user }}/.ssh"
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: "0700"

    # LOKALER TASK: Finde alle relevanten Yubikey Public Keys.
    - name: Find all local SSH public keys for system_user
      find:
        paths: "{{ lookup('env','HOME') }}/.ssh"
        patterns: "id_ed25519-sk_{{ system_user }}_ethnode*.pub"
        file_type: file
      register: ssh_keys
      delegate_to: localhost
      become: false

    # Gefundene Public Keys auf Zielhost installieren.
    - name: Install all public keys for system_user
      authorized_key:
        user: "{{ system_user }}"
        state: present
        key: "{{ lookup('file', item.path) }}"
      loop: "{{ ssh_keys.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
