---
##
## Playbook: OS-Hardening, SSH-Setup und UFW-Basisregeln
## Ziel: Frischen Host vorbereiten durch:
##   - UFW mit Default-Deny aktivieren.
##   - Reboot zum Anwenden aller Änderungen.
##
## Ausführen (Beispiel):
## ansible-playbook -i inventory/hosts.yml --extra-vars="ansible_port=22" 04_setup_os_firewall_ssh.yml
##
## Targets: Inventory-Gruppe "ethnode"
## Privilege: become nötig für Konfiguration von Firewall und sshd.
## Voraussetzungen:
##   - Host ist über SSH Port 22 erreichbar.
##
## Sicherheitshinweis:
##   - Host soll via SSH Port 19497 nur im lokalen Netzwerk / per VPN erreichbar sein.
##   - Empfehlung: fail2ban installieren.
##

- name: Setup OS - Config SSH Firewall User
  hosts: ethnode
  become: true
  gather_facts: true

  tasks:
    # sshd sichern (Port/Auth), Vorlage anpassen und Handler triggern.
    - name: Make local copy of current sshd_config
      copy:
        remote_src: yes
        src: "/etc/ssh/sshd_config"
        dest: "/etc/ssh/sshd_config_backup_{{ ansible_date_time.iso8601 }}"

    - name: sshd configuration file update
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        backup: yes
        owner: root
        group: root
        mode: "0644"
        validate: /usr/sbin/sshd -T -f %s
      notify: restart-sshd

    # SSH erlauben.
    - name: UFW - Allow SSH
      ufw:
        rule: allow
        port: 19497
        proto: tcp
        comment: SSH access

    # Ethereum Node Ports erlauben.
    - name: UFW - Allow nimbusCL TCP listening port
      ufw:
        rule: allow
        port: 9000
        proto: tcp
        comment: nimbusCL TCP listening port

    - name: UFW - Allow nimbusCL UDP listening port
      ufw:
        rule: allow
        port: 9000
        proto: udp
        comment: nimbusCL UDP listening port

    - name: UFW - Allow rethEL discv5 discovery port
      ufw:
        rule: allow
        port: 9200
        proto: udp
        comment: rethEL UDP discv5 discovery port

    - name: UFW - Allow rethEL TCP listening port
      ufw:
        rule: allow
        port: 30303
        proto: tcp
        comment: rethEL TCP listening port

    - name: UFW - Allow rethEL UDP listening port
      ufw:
        rule: allow
        port: 30303
        proto: udp
        comment: rethEL UDP listening port

    # UFW Default-Deny aktivieren.
    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming

  handlers:
    # sshd neu starten, wenn Config geändert wurde.
    - name: restart-sshd
      service:
        name: sshd
        state: restarted
