---
##
## Playbook: OS Update
## Ziel: System aktualisieren.
##
## Ausführen (Beispiel):
## ansible-playbook -i inventory/hosts.yml 06_update_os.yml
##
## Targets: Inventory-Gruppe "ethnode"
## Privilege: become nötig für Systemkonfiguration.
##

- name: Update OS
  hosts: ethnode
  become: true
  gather_facts: false

  tasks:
    # Paket-Index aktualisieren und System-Pakete upgraden und bereinigen.
    - name: Run <apt update && apt dist-upgrade>
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    # Zeigen, ob ein Reboot erforderlich ist (z.B. nach Kernel-Updates).
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Read reboot reason
      slurp:
        path: /var/run/reboot-required
      register: reboot_reason
      when: reboot_required_file.stat.exists

    - name: Display reboot status
      debug:
        msg: >-
          {% if reboot_required_file.stat.exists %}
            Reboot is required! Reason: {{ reboot_reason.content | b64decode | trim }}
          {% else %}
            No reboot required.
          {% endif %}
