---
##
## Playbook: Nimbus installieren (Consensus Layer)
## Ziel: Host mit Nimbus CL provisionieren durch:
##   - Anlegen von Service-Usern und Verzeichnissen.
##   - Basis-Pakete (chrony) installieren.
##   - neuste Nimbus-Binaries von GitHub Releases laden.
##   - Beacon Binary sicher nach nimbus_cl_bin_dir legen.
##
## Ausführen (Beispiel):
## ansible-playbook -i inventory/hosts.yml 11_install_nimbus.yml
##
## Targets: Inventory-Gruppe "ethnode"
## Privilege: become nötig für Benutzerverwaltung und Systemmanagement.
## Variablen:
##   - nimbus_cl_system_user
##   - nimbus_cl_bin_dir
##   - nimbus_log_dir, nimbus_cl_log_file
##   - nimbus_cl_data_dir
##   - nimbus_version: steuert Release-Tag (z.B. v25.12.0)
##   - nimbus_cl_rest_port
##   - system_user
## Templates:
##   - nimbusCL.service.j2
## Voraussetzungen:
##   - Outbound Internet zu GitHub.
##

- name: Install Nimbus
  hosts: ethnode
  become: true
  gather_facts: false

  vars_files:
    - vars/config_project.yml
    - vars/config_untracked.yml

  tasks:
    #################
    # Service-Gruppen und Service-User für Nimbus anlegen

    - name: Ensure group for Nimbus CL exists
      group:
        name: "{{ nimbus_cl_system_user }}"
        state: present

    - name: Ensure dedicated group for shared JWT access exists
      group:
        name: jwt
        state: present

    - name: Add the user for Nimbus CL
      user:
        name: "{{ nimbus_cl_system_user }}"
        group: "{{ nimbus_cl_system_user }}"
        groups: jwt
        create_home: yes
        shell: /bin/bash

    ##################
    # Sicherstellen, dass chrony für Zeit-Sync installiert ist

    - name: Ensure chrony package is installed
      package:
        name: chrony
        state: present

    - name: Ensure chrony service is started and enabled
      service:
        name: chrony
        state: started
        enabled: yes

    ################
    # Verzeichnisse für Binary, Daten und Logs mit korrekten Rechten anlegen

    - name: Create the Nimbus CL bin directory
      file:
        path: "{{ nimbus_cl_bin_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Make sure the Nimbus CL data directory exists
      file:
        path: "{{ nimbus_cl_data_dir }}"
        state: directory
        owner: "{{ nimbus_cl_system_user }}"
        group: "{{ nimbus_cl_system_user }}"
        mode: "0700"

    - name: Ensure the log file directory exists
      file:
        path: "{{ nimbus_log_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Ensure log files exist with correct ownership
      file:
        path: "{{ nimbus_log_dir }}/{{ nimbus_cl_log_file }}"
        state: touch
        owner: "{{ nimbus_cl_system_user }}"
        group: "{{ nimbus_cl_system_user }}"
        mode: "0644"

    ###############
    # Neueste Release-Asset von GitHub ermitteln und laden

    - name: Get the latest Nimbus Eth2 release URL for Linux amd64
      uri:
        url: "https://api.github.com/repos/status-im/nimbus-eth2/releases/latest"
        method: GET
        return_content: yes
        body_format: json
      register: release_data

    - name: Set binaries_url from the release data
      set_fact:
        binaries_urls: "{{ release_data.json.assets | map(attribute='browser_download_url') | select('match', '^https://github.com/status-im/nimbus-eth2/releases/download/v[0-9]+\\.[0-9]+\\.[0-9]+/nimbus-eth2_Linux_amd64_.*\\.tar\\.gz$') | list }}"

    - name: Set first match
      set_fact:
        binaries_url: "{{ binaries_urls | first | default('') }}"

    - name: Display binaries_url
      debug:
        msg: "{{ binaries_url }}"

    - name: Download the Nimbus Eth2 tar.gz
      get_url:
        url: "{{ binaries_url }}"
        dest: "/tmp/nimbus.tar.gz"

    - name: Verify tarball is gzip
      command:
        cmd: "file /tmp/nimbus.tar.gz"
      register: tar_type
      changed_when: false

    - name: Fail if tarball is not gzip
      fail:
        msg: "Downloaded file is not a gzip archive"
      when: "'gzip compressed' not in tar_type.stdout"

    # Temporär entpacken.
    - name: Ensure the destination directory exists
      file:
        path: "/home/{{ system_user }}/nimbus"
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: "0755"

    - name: Extract Nimbus Eth2 tar.gz to the home directory
      unarchive:
        src: "/tmp/nimbus.tar.gz"
        dest: "/home/{{ system_user }}/nimbus"
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    # Entfernen der heruntergeladenen Datei.
    - name: Cleanup downloaded tar.gz
      file:
        path: "/tmp/nimbus.tar.gz"
        state: absent

    ###################
    # Nimbus Binary ersetzen

    # Nimbus Binary in den Zielordner verschieben und restriktive Rechte setzen.
    - name: Copy the binary to {{ nimbus_cl_binary_path }}
      copy:
        src: "/home/{{ system_user }}/nimbus/build/nimbus_beacon_node"
        dest: "{{ nimbus_cl_binary_path }}"
        remote_src: yes
        owner: "{{ nimbus_cl_system_user }}"
        group: "{{ nimbus_cl_system_user }}"
        mode: "0700"

    # Temorären nimbus-Ornder im Home-Verzeichnis entfernen.
    - name: Cleanup nimbus folder
      file:
        path: "/home/{{ system_user }}/nimbus"
        state: absent

    ###################
    # Installierte Version anzeigen

    - name: Check nimbus_beacon_node version
      command:
        cmd: "{{ nimbus_cl_binary_path }} --version"
      register: nimbus_version
      changed_when: false

    - name: Display nimbus_beacon_node version
      debug:
        msg: "{{ nimbus_version.stdout }}"
