---
##
## Playbook: Nimbus als Service konfigurieren und starten
## Ziel: Nimbus-Unit-Template sicher deployen durch:
##   - Service stoppen.
##   - Template kopieren.
##   - systemd reload und Service neu starten.
##
## Ausführen (Beispiel):
## ansible-playbook -i inventory/hosts.yml 13_configure_and_run_nimbus.yml
##
## Targets: Inventory-Gruppe "ethnode"
## Privilege: become nötig für Systemanagement.
## Variablen:
##   - nimbus_cl_system_user
##   - nimbus_ext_ip (wird automatisch ermittelt falls leer)
##   - nimbus_cl_rest_address
##   - nimbus_cl_rest_port
## Templates:
##   - templates/nimbusCL.service.j2
##

- name: Configure Nimbus and copy service file
  hosts: ethnode
  become: true
  gather_facts: false

  vars_files:
    - vars/config_project.yml
    - vars/config_untracked.yml

  tasks:
    ##############################
    # Fee Recipient Adresse für Rocket Pool Validatoren ermitteln, falls vorhanden.

    - name: Check if Rocket Pool fee recipient file exists
      stat:
        path: "/home/{{ system_user }}/.rocketpool/data/validators/rp-fee-recipient.txt"
      register: rp_fee_file

    - name: Read Rocket Pool fee recipient address
      slurp:
        src: "/home/{{ system_user }}/.rocketpool/data/validators/rp-fee-recipient.txt"
      register: rp_fee_recipient_raw
      when: rp_fee_file.stat.exists

    - name: Set fee recipient fact
      set_fact:
        fee_recipient_wallet_address: "{{ rp_fee_recipient_raw.content | b64decode | trim }}"
      when: rp_fee_file.stat.exists

    - name: Display fee recipient address
      debug:
        msg: "Fee Recipient Address: {{ fee_recipient_wallet_address }}"

    ##############################
    # Externe IP-Adresse ermitteln, falls nicht angegeben.
    - block:
        - name: Fetch public IP
          uri:
            url: https://api.ipify.org
            method: GET
            return_content: yes
            status_code: 200
          register: public_ip_output
          ignore_errors: yes

        - name: Set the public ip
          set_fact:
            nimbus_ext_ip: "{{ public_ip_output.content }}"
          when: public_ip_output.status == 200
      when: not nimbus_ext_ip

    # IP-Adresse anzeigen.
    - name: Show nimbus_ext_ip
      debug:
        var: nimbus_ext_ip

    ##############################
    # Stop Nimbus

    # Service stoppen, bevor Units ersetzt werden.
    - name: Stop Nimbus service
      systemd:
        name: "{{ nimbus_cl_system_user }}"
        state: stopped
      failed_when: false # Fehler ignorieren, falls Service noch nicht existiert.

    ##############################
    # Copy Service Template File

    # Template nach /etc/systemd/system kopieren.
    - name: Copy service script
      template:
        src: "templates/{{ nimbus_cl_system_user }}.service.j2"
        dest: "/etc/systemd/system/{{ nimbus_cl_system_user }}.service"
        owner: root
        group: root
        mode: "0644"

    ###################
    # Starte Nimbus

    # Service nach erfolgreicher Installation starten.
    - name: Start Nimbus service and make sure it is enabled on reboots
      systemd:
        name: "{{ nimbus_cl_system_user }}"
        state: restarted
        enabled: yes
        daemon_reload: yes

    ###################
    # Prüfen, ob Nimbus erfolgreich gestartet wurde und Version anzeigen

    - name: Wait for Nimbus REST API to respond
      uri:
        url: "http://{{ nimbus_cl_rest_address }}:{{ nimbus_cl_rest_port }}/eth/v1/node/version"
        method: GET
        status_code: 200
        return_content: yes
      register: node_version
      retries: 12 # Number of polling attempts
      delay: 5 # Seconds between retries
      until: node_version.status == 200

    - name: Display Nimbus node version if available
      debug:
        msg: >-
          {% if node_version.status == 200 %}
            Running Nimbus version is: {{ node_version.content | from_json | json_query('data.version') }}
          {% else %}
            Nimbus REST API not reachable
          {% endif %}

    - name: Make sure Nimbus is running
      assert:
        that: node_version.content is defined and node_version.content != ""
        fail_msg: "Nimbus is not running"
        success_msg: "Nimbus successfully started"
