---
##
## Playbook: Nimbus als Service konfigurieren und starten
## Ziel: Nimbus-Unit-Template sicher deployen durch:
##   - Service stoppen.
##   - Template kopieren.
##   - systemd reload und Service neu starten.
##
## Ausführen (Beispiel):
## ansible-playbook -i inventory/hosts.yml 13_configure_nimbus.yml
##
## Targets: Inventory-Gruppe "ethnode"
## Privilege: become nötig für Systemanagement.
## Variablen:
##   - nimbus_cl_system_user
##   - nimbus_ext_ip (wird automatisch ermittelt falls leer)
## Templates:
##   - templates/nimbusCL.service.j2
##

- name: Configure Nimbus and copy service file
  hosts: ethnode
  become: true
  gather_facts: false

  vars_files:
    - vars/config_project.yml
    - vars/config_untracked.yml

  tasks:
    # IP-Adresse ermitteln, falls nicht angegeben.
    - name: Get IP address to bind to if not provided
      include_tasks: "tasks/network.yml"
      when: not nimbus_ext_ip

    # IP-Adresse anzeigen.
    - name: Show nimbus_ext_ip
      debug:
        var: nimbus_ext_ip

    # Service stoppen, bevor Units ersetzt werden.
    - name: Stop Nimbus service
      systemd:
        name: "{{ nimbus_cl_system_user }}"
        state: stopped

    ##############################
    # Copy Service Template File

    # Template nach /etc/systemd/system kopieren.
    - name: Copy service script
      template:
        src: "templates/{{ nimbus_cl_system_user }}.service.j2"
        dest: "/etc/systemd/system/{{ nimbus_cl_system_user }}.service"
        owner: root
        group: root
        mode: "0644"

    ###################
    # Starte nimbus

    # Service nach erfolgreicher Installation starten.
    - name: Start Nimbus service and make sure it is enabled on reboots
      systemd:
        name: "{{ nimbus_cl_system_user }}"
        state: restarted
        enabled: yes
        daemon_reload: yes

    # Beacon booten lassen, dann die Version via REST API abfragen.
    - name: Pause for 30 seconds for Nimbus to start
      pause:
        seconds: 30

    - name: Fetch and display the Nimbus node version
      shell: |
        curl -s http://{{ server_ip }}:{{ nimbus_cl_rest_port }}/eth/v1/node/version | jq -r '.data.version'
      register: node_version
      failed_when: node_version.rc != 0
      changed_when: false

    - name: Make sure Nimbus is running
      assert:
        that: node_version.stdout is defined and node_version.stdout != ""
        fail_msg: "'Nimbus is not running"
        success_msg: "Running Nimbus version is: {{ node_version.stdout }}"
