---
##
## Playbook: Reth aktualisieren und neu starten (Execution Layer)
## Ziel: Reth auf gewünschte Version aktualisieren durch:
##   - gewünschte Version von GitHub Releases herunterladen.
##   - laufenden Service stoppen.
##   - Binary ersetzen und Service neu starten.
##
## Ausführen (Beispiel):
## ansible-playbook -i inventory/hosts.yml 36_update_reth.yml
##
## Targets: Inventory-Gruppe "ethnode"
## Privilege: become nötig für Systemmanagement.
## Variablen: vars/config_project.yml
##   - reth_system_user
##   - reth_bin_dir, reth_binary_path
##   - reth_data_dir
##   - reth_version: steuert Release-Tag (z.B. v1.9.3)
## Template:
##   - templates/rethEL.service.j2
## Voraussetzungen:
##   - Outbound Internet zu GitHub.
##

- name: Update reth binary and restart Service
  hosts: ethnode
  become: true
  gather_facts: false

  vars_files:
    - vars/config_project.yml
    - vars/config_untracked.yml

  tasks:
    ################
    # Update reth

    # Gesetzte Reth Binary Version von GitHub Releases herunterladen.
    - name: Download reth binary "{{ reth_version }}" from GitHub releases
      ansible.builtin.get_url:
        url: "https://github.com/paradigmxyz/reth/releases/download/{{ reth_version }}/reth-{{ reth_version }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/tmp/reth.tar.gz"

    - name: Verify tarball is gzip
      ansible.builtin.command:
        cmd: "file /tmp/reth.tar.gz"
      register: tar_type
      changed_when: false

    - name: Fail if tarball is not gzip
      ansible.builtin.fail:
        msg: "Downloaded file is not a gzip archive"
      when: "'gzip compressed' not in tar_type.stdout"

    # Temporär entpacken.
    - name: Ensure the destination directory exists
      ansible.builtin.file:
        path: "/home/{{ system_user }}/reth"
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: "0755"

    - name: Extract reth tar.gz to the home directory
      ansible.builtin.unarchive:
        src: "/tmp/reth.tar.gz"
        dest: "/home/{{ system_user }}/reth"
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    # Download-Verzeichnis aufräumen.
    - name: Cleanup downloaded reth.tar.gz
      ansible.builtin.file:
        path: "/tmp/reth.tar.gz"
        state: absent

    ###########
    # Stop Reth and copy binary

    # Service stoppen, um Binary sicher zu ersetzen.
    - name: Stop "{{ reth_system_user }}" service
      systemd:
        name: "{{ reth_system_user }}"
        state: stopped

    # Binary in den Zielordner verschieben und restriktive Rechte setzen.
    - name: Copy the binary to {{ reth_binary_path }}
      copy:
        src: "/home/{{ system_user }}/reth/reth"
        dest: "{{ reth_binary_path }}"
        remote_src: yes
        owner: "{{ reth_system_user }}"
        group: "{{ reth_system_user }}"
        mode: "0700"

    # Temorären reth-Ordner im Home-Verzeichnis entfernen.
    - name: Cleanup reth folder
      ansible.builtin.file:
        path: "/home/{{ system_user }}/reth"
        state: absent

    # Installierte Version anzeigen.
    - name: Check reth version
      ansible.builtin.command:
        cmd: "{{ reth_binary_path }} --version"
      register: reth_version
      changed_when: false

    - name: Display reth version
      ansible.builtin.debug:
        msg: "{{ reth_version.stdout }}"

    ##############################
    # Copy Service Template Files

    # systemd-Unit aus Template aktualisieren.
    - name: Copy service script
      template:
        src: templates/{{ reth_system_user }}.service.j2
        dest: /etc/systemd/system/{{ reth_system_user }}.service
        owner: root
        group: root
        mode: "0644"
      notify: daemon-reload

    # Service neu starten, damit das neue Binary läuft.
    - name: Start "{{ reth_system_user }}" service
      systemd:
        name: "{{ reth_system_user }}"
        state: restarted

  handlers:
    # systemd neu laden, wenn Templates geändert wurden.
    - name: daemon-reload
      systemd:
        daemon_reload: yes
