---
##
## Playbook: UFW-Regeln für Rocket Pool Smartnode konfigurieren
##
## Ausführen (Beispiel):
## ansible-playbook -i inventory/hosts.yml 41_update_firewall.yml
##
## Targets: Inventory-Gruppe "ethnode"
## Privilege: become nötig für Konfiguration von Firewall.
## Variablen: vars/config_project.yml
##   - reth_rpc_http_port
##   - reth_rpc_ws_port
##   - reth_metrics_port
##   - nimbus_cl_rest_port
##   - nimbus_cl_metrics_port
##

- name: Update UFW Firewall Rules for Rocket Pool Smartnode
  hosts: ethnode
  become: true
  gather_facts: false

  vars_files:
    - vars/config_project.yml

  tasks:
    ###################
    # Firewall: UFW für Rocket Pool Smartnode konfigurieren

    - name: Get Rocket Pool docker network subnet
      shell: >
        docker inspect rocketpool_net | grep -Po "(?<=\"Subnet\": \")[0-9./]+"
      register: rp_net_result
      changed_when: false

    - name: Set Rocket Pool docker network subnet fact
      set_fact:
        rp_net: "{{ rp_net_result.stdout }}"

    - name: Display Rocket Pool docker network subnet
      debug:
        msg: "{{ rp_net }}"

    - name: Allow Rocket Pool access to Reth RPC via HTTP ({{ reth_rpc_http_port }})
      ufw:
        rule: allow
        src: "{{ rp_net }}"
        port: "{{ reth_rpc_http_port }}"
        proto: tcp
        comment: "Allow Rocketpool Docker to access Reth RPC via HTTP"

    - name: Allow Rocket Pool access to Reth RPC via WS ({{ reth_rpc_ws_port }})
      ufw:
        rule: allow
        src: "{{ rp_net }}"
        port: "{{ reth_rpc_ws_port }}"
        proto: tcp
        comment: "Allow Rocketpool Docker to access Reth RPC via WS"

    - name: Allow Rocket Pool access to Reth metrics ({{ reth_metrics_port }})
      ufw:
        rule: allow
        src: "{{ rp_net }}"
        port: "{{ reth_metrics_port }}"
        proto: tcp
        comment: "Allow Rocketpool Docker to access Reth metrics"

    - name: Allow Rocket Pool access to Nimbus REST via HTTP ({{ nimbus_cl_rest_port }})
      ufw:
        rule: allow
        src: "{{ rp_net }}"
        port: "{{ nimbus_cl_rest_port }}"
        proto: tcp
        comment: "Allow Rocketpool Docker to access Nimbus REST via HTTP"

    - name: Allow Rocket Pool access to Nimbus metrics ({{ nimbus_cl_metrics_port }})
      ufw:
        rule: allow
        src: "{{ rp_net }}"
        port: "{{ nimbus_cl_metrics_port }}"
        proto: tcp
        comment: "Allow Rocketpool Docker to access Nimbus metrics"

    - name: Allow Rocket Pool access to Prometheus node-exporter (9103)
      ufw:
        rule: allow
        src: "{{ rp_net }}"
        port: "9103"
        proto: tcp
        comment: "Allow Rocketpool Docker to access Prometheus node-exporter"

    - name: Ensure UFW is enabled
      ufw:
        state: enabled
