---
##
## Playbook: Tuning der Systemparameter
##
## Ausführen (Beispiel):
## ansible-playbook -i inventory/hosts.yml 43_tune_system.yml
##
## Targets: Inventory-Gruppe "ethnode"
## Privilege: become nötig für Änderungen der Kernelparameter.
## Variablen: vars/config_project.yml
##   - system_user
##

- name: Configure VM memory settings for Ethereum node
  hosts: ethnode
  become: true
  gather_facts: false

  vars_files:
    - vars/config_project.yml

  tasks:
    ##############################
    # Configure VM memory settings for Ethereum node

    - name: Ensure sysctl config file exists
      file:
        path: /etc/sysctl.d/99-vm-tuning.conf
        state: touch
        mode: "0644"

    - name: Set vm.swappiness
      lineinfile:
        path: /etc/sysctl.d/99-vm-tuning.conf
        regexp: "^vm.swappiness"
        line: "vm.swappiness = 1"
        state: present
        create: yes

    - name: Set vm.vfs_cache_pressure
      lineinfile:
        path: /etc/sysctl.d/99-vm-tuning.conf
        regexp: "^vm.vfs_cache_pressure"
        line: "vm.vfs_cache_pressure = 50"
        state: present
        create: yes

    - name: Apply sysctl settings
      command: sysctl --system
      register: sysctl_output
      changed_when: "'Reloading sysctl' in sysctl_output.stdout"

    # noatime,inode64 für die NVMe hinzufügen, um die Leistung zu verbessern.
    - name: Ensure /mnt/nvme entry in /etc/fstab is tuned for rethEL
      lineinfile:
        path: /etc/fstab
        # Matches exactly: device, /mnt/nvme, xfs, and the space before options
        regexp: '^(\S+\s+/mnt/nvme\s+xfs)(\s+).*'
        line: '\1\2defaults,noatime,inode64 0 0'
        backrefs: yes
        state: present

    # Systemd neu laden, damit die neuen fstab-Einträge erkannt werden
    - name: Reload systemd to pick up new fstab entries
      command: systemctl daemon-reload

    # Sicherstellen, dass die neue fstab-Konfiguration angewendet werden kann
    - name: Remount /mnt/nvme with updated options
      command: mount -o remount /mnt/nvme
      ignore_errors: yes
      register: remount_result

    - name: Fail if /mnt/nvme cannot be mounted
      fail:
        msg: "/mnt/nvme could not be mounted! Check /etc/fstab entry."
      when: remount_result.rc != 0
