---
all:
  children:
    servers:
      hosts:
        ethnode:
          project_name: ethnode
          ansible_host: 192.168.101.99
          ansible_user: automation_admin
          ansible_ssh_private_key_file: "/var/lib/automation_admin/.ssh/id_ed25519"
          ansible_port: 22
          ansible_python_interpreter: auto_silent
