---
all:
  children:
    servers:
      hosts:
        ethnode:
          project_name: ethnode
          ansible_host: 192.168.101.99
          ansible_user: automation_admin
          ansible_ssh_private_key_file: "~/.ssh/id_ed25519-sk_ansible_ethnode_YubiKey5C-nano_2026-02-10_01"
          ansible_port: 22
          ansible_python_interpreter: auto_silent
