---
- name: Fetch public IP
  uri:
    url: https://api.ipify.org
    method: GET
    return_content: yes
    status_code: 200
  register: public_ip_output
  ignore_errors: True

- name: Set the public ip
  set_fact:
    nimbus_ext_ip: "{{ public_ip_output.content }}"
  when: public_ip_output.status == 200
