---
##########################################
# SYSTEM
##########################################

automation_admin_uid: 11011
automation_admin_home: /home/automation_admin
automation_admin_password_hash: "" # overridden by vars/config_untracked.yml

sys_packages:
  - chrony
  - git
  - curl
  - gnupg
  - jq
  - ccze
  - ufw
  - glances
  - zip
  - unzip
  - tree

##########################################
# SERVER
##########################################

## User
system_user: "" # overridden by vars/config_untracked.yml

# Network
server_fqdn_hostname: "ethnode.local"
localhost_ip: "127.0.0.1"
external_ip: "" # overridden by vars/config_untracked.yml

# Language and Timezone
config_system_locale: "de_CH.UTF-8"
config_system_language: "en_US.UTF-8"
config_system_timezone: "Europe/Zurich"

# JWT
jwtsecret_path: "/var/lib/jwtsecrets/janode.hex"

##########################################
# ETH ETHEREUM NETWORK
##########################################

network: "hoodi" # set up an environment, e.g "hoodi" or "mainnet"
fee_recipient_wallet_address: "" # overridden by vars/config_untracked.yml

##########################################
# RETH EXECUTION LAYER
##########################################
# Latest release at "https://github.com/paradigmxyz/reth/releases/latest"

reth_version: "" # leave empty for latest version, or set wanted version, e.g. "v1.9.3"
reth_system_user: rethEL
reth_bin_dir: "/opt/reth/bin"
reth_binary_path: "{{ reth_bin_dir }}/reth" # Full path to the binary
reth_home_dir: "/mnt/nvme/rethEL"
reth_data_dir: "/mnt/nvme/rethEL/data"
reth_log_dir: "/var/log/reth"
reth_log_level: info # debug, info, warn, error
reth_ext_port: 30303
reth_ext_discv5_port: 9200
reth_max_peers_out: 40
reth_max_peers_in: 24
reth_rpc_http_port: 8545
reth_rpc_ws_port: 8546
reth_metrics_address: "{{ localhost_ip }}"
reth_metrics_port: 9001
reth_jwtsecret_path: "{{ jwtsecret_path }}"
reth_authrpc_addr: "{{ localhost_ip }}"
reth_authrpc_port: 8551
reth_http_corsdomain: "" # empty = no CORS (recommended for localhost-only), or "http://localhost, http://127.0.0.1" for browser tools
reth_ws_origins: "" # empty = no origin checking (recommended for localhost-only), or "http://localhost, http://127.0.0.1" for browser tools

##########################################
# NIMBUS CONSENSUS LAYER
##########################################
# Latest release at "https://github.com/status-im/nimbus-eth2/releases/latest"

nimbus_cl_system_user: "nimbusCL"
nimbus_cl_bin_dir: /opt/nimbusCL/bin
nimbus_cl_data_dir: /opt/nimbusCL/data
nimbus_cl_rest_port: 5052
nimbus_cl_metrics_port: 8008
nimbus_cl_node_name: JaNode
nimbus_ext_tcp_port: 9000
nimbus_ext_udp_port: 9000
nimbus_ext_ip: "{{ external_ip }}"
nimbus_max_peers: 100
nimbus_hard_max_peers: 136
nimbus_jwt_secret_path: "{{ jwtsecret_path }}"
el_http: "http://{{ localhost_ip }}:{{ reth_authrpc_port }}"

nimbus_validator_system_user: "nimbusValidator"
nimbus_validator_bin_dir: /opt/nimbusValidator/bin
nimbus_validator_data_dir: /opt/nimbusValidator/data
nimbus_validator_secrets_dir: /opt/nimbusValidator/secrets
nimbus_validator_validators_dir: /opt/nimbusValidator/validators
nimbus_validator_keys_dir: /opt/nimbusValidator/validator_keys
nimbus_validator_graffiti: "janode"

# Nimbus Logging
nimbus_log_level: "NOTICE" # DEBUG, INFO, NOTICE, WARN, ERROR
nimbus_log_dir: "/var/log/nimbus"
nimbus_cl_log_file: "nimbusCL.jsonl"
nimbus_validator_log_file: "nimbusValidator.jsonl"
