---
##########################################
# SYSTEM
##########################################

sys_packages:
  - chrony
  - git
  - curl
  - gnupg
  - jq
  - ccze
  - ufw
  - glances
  - zip
  - unzip
  - tree

##########################################
# SERVER
##########################################

## User
system_user: "rp"
automation_admin_uid: 11011
automation_admin_home: /home/automation_admin

# Network
server_fqdn_hostname: "ethnode.local"
localhost_ip: "0.0.0.0"

# Language and Timezone
config_system_locale: "de_CH.UTF-8"
config_system_language: "en_US.UTF-8"
config_system_timezone: "Europe/Zurich"

# JWT
jwtsecret_path: "/var/lib/jwtsecrets/jwt.hex"

##########################################
# ETH ETHEREUM NETWORK
##########################################

network: "mainnet" # set up an environment, e.g "hoodi" or "mainnet"
fee_recipient_wallet_address: "" # overridden by vars/config_untracked.yml

##########################################
# RETH EXECUTION LAYER
##########################################
# Latest release at "https://github.com/paradigmxyz/reth/releases/latest"

reth_version: "" # leave empty for latest version, or set wanted version, e.g. "v1.9.3"
reth_system_user: rethEL
reth_bin_dir: "/opt/reth/bin"
reth_binary_path: "{{ reth_bin_dir }}/reth" # Full path to the binary
reth_home_dir: "/mnt/nvme/rethEL"
reth_data_dir: "/mnt/nvme/rethEL/data"
reth_log_dir: "/var/log/reth"
reth_log_level: info # debug, info, warn, error
reth_ext_port: 30303
reth_ext_discv5_port: 9200
reth_max_peers_out: 40
reth_max_peers_in: 24
reth_rpc_http_port: 8545
reth_rpc_ws_port: 8546
reth_metrics_address: "{{ localhost_ip }}"
reth_metrics_port: 9105
reth_jwtsecret_path: "{{ jwtsecret_path }}"
reth_authrpc_addr: "{{ localhost_ip }}"
reth_authrpc_port: 8551
reth_http_corsdomain: "" # empty = no CORS (recommended for localhost-only), or "http://localhost, http://127.0.0.1" for browser tools
reth_ws_origins: "" # empty = no origin checking (recommended for localhost-only), or "http://localhost, http://127.0.0.1" for browser tools

##########################################
# NIMBUS CONSENSUS LAYER
##########################################
# Latest release at "https://github.com/status-im/nimbus-eth2/releases/latest"

nimbus_cl_system_user: "nimbusCL"
nimbus_cl_base_dir: "/opt/nimbusCL"
nimbus_cl_bin_dir: "{{ nimbus_cl_base_dir }}/bin"
nimbus_cl_data_dir: "{{ nimbus_cl_base_dir }}/data"
nimbus_cl_rest_address: "{{ localhost_ip }}"
nimbus_cl_rest_port: 5052
nimbus_cl_metrics_address: "{{ localhost_ip }}"
nimbus_cl_metrics_port: 9100
nimbus_cl_node_name: JaNode
nimbus_ext_tcp_port: 9000
nimbus_ext_udp_port: 9000
nimbus_ext_ip: "" # leave empty to auto-detect, or set to specific IP
nimbus_max_peers: 100
nimbus_hard_max_peers: 136
nimbus_jwt_secret_path: "{{ jwtsecret_path }}"
nimbus_checkpoint_sync_url: "https://mainnet-checkpoint-sync.stakely.io" # e.g. https://mainnet-checkpoint-sync.stakely.io
el_http: "http://{{ localhost_ip }}:{{ reth_authrpc_port }}"

# Nimbus Logging
nimbus_log_level: "NOTICE" # DEBUG, INFO, NOTICE, WARN, ERROR
nimbus_log_dir: "/var/log/nimbus"
nimbus_cl_log_file: "nimbusCL.jsonl"
